packages:
  - "."
  - "src/frontend"

allowBuilds:
  '@biomejs/biome': true
  '@clerk/shared': true
  '@firebase/util': set this to true or false
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
