/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIQuery {
  'queryText' : string,
  'userId' : Principal,
  'response' : string,
  'timestamp' : bigint,
}
export interface ActiveSession {
  'loginTimestamp' : bigint,
  'deviceName' : string,
  'sessionId' : string,
  'location' : string,
}
export interface BiometricSettings {
  'biometricType' : [] | [string],
  'enabled' : boolean,
}
export interface BusinessApplication {
  'status' : BusinessApplicationStatus,
  'termsAccepted' : boolean,
  'createdAt' : bigint,
  'rejectionReason' : [] | [string],
  'businessName' : string,
  'businessType' : string,
  'description' : string,
  'updatedAt' : bigint,
}
export type BusinessApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CompilationStatus {
  'obfuscationLayer' : string,
  'verificationTimestamp' : bigint,
  'tooltipNote' : string,
}
export type DeletionStatus = {
    'pending' : { 'scheduledDeletionTime' : bigint }
  } |
  { 'not_requested' : null } |
  { 'finalized' : null };
export interface DirectDeposit {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'isTest' : boolean,
  'userPrincipal' : Principal,
  'clearAt' : bigint,
  'amount' : bigint,
}
export interface DirectDepositAccount {
  'status' : string,
  'routingNumber' : string,
  'createdAt' : bigint,
  'accountNumber' : string,
}
export interface Dispute {
  'id' : string,
  'status' : DisputeStatus,
  'submitterPrincipal' : Principal,
  'createdAt' : bigint,
  'resolution' : [] | [string],
  'transactionTimestamp' : bigint,
  'updatedAt' : bigint,
  'counterpartyPrincipal' : Principal,
  'reason' : string,
}
export type DisputeStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'rejected' : null };
export interface EncryptionEvent {
  'dataType' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export type ExternalBlob = Uint8Array;
export interface FraudAlert {
  'resolved' : boolean,
  'userId' : Principal,
  'timestamp' : bigint,
  'severity' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'reason' : string,
}
export interface GDPRAuditEvent {
  'principal' : Principal,
  'timestamp' : bigint,
  'eventType' : GDPRAuditEventType,
}
export type GDPRAuditEventType = { 'deletion_finalized' : null } |
  { 'deletion_requested' : null } |
  { 'deletion_cancelled' : null } |
  { 'export_requested' : null };
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type KYCStatus = { 'notSubmitted' : null } |
  { 'verified' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface MoneyRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'toUser' : Principal,
  'message' : string,
  'paidTipId' : [] | [bigint],
  'timestamp' : bigint,
  'fromUser' : Principal,
  'amount' : bigint,
}
export interface PaymentMethod {
  'id' : string,
  'methodType' : PaymentMethodType,
  'last4' : string,
  'bankName' : [] | [string],
  'accountType' : [] | [string],
  'addedAt' : bigint,
  'stripeVerificationStatus' : string,
  'brand' : [] | [string],
}
export type PaymentMethodType = { 'bankAccount' : null } |
  { 'card' : null };
export interface PayoutRecord {
  'id' : string,
  'distributions' : Array<[Principal, bigint]>,
  'notes' : string,
  'timestamp' : bigint,
  'managerPrincipal' : Principal,
}
export type PinCheckResult = { 'verified' : null } |
  { 'blocked' : bigint } |
  { 'incorrect' : bigint };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type RecurringFrequency = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface RecurringPayment {
  'id' : bigint,
  'owner' : Principal,
  'lastRunAt' : [] | [bigint],
  'createdAt' : bigint,
  'totalRuns' : bigint,
  'enabled' : boolean,
  'toUser' : Principal,
  'message' : string,
  'nextRunTime' : bigint,
  'frequency' : RecurringFrequency,
  'amount' : bigint,
}
export type RequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'declined' : null };
export type SavingsDirection = { 'fromSavings' : null } |
  { 'toSavings' : null };
export interface SavingsTransaction {
  'id' : bigint,
  'direction' : SavingsDirection,
  'owner' : Principal,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface SearchResult {
  'bio' : string,
  'username' : string,
  'isVerified' : boolean,
  'photo' : [] | [ExternalBlob],
}
export interface SecurityEvent {
  'userId' : Principal,
  'timestamp' : bigint,
  'details' : string,
  'eventType' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SmartReceipt {
  'month' : bigint,
  'userId' : Principal,
  'generatedAt' : bigint,
  'professionalTips' : Array<Tip>,
  'year' : bigint,
  'totalAmount' : bigint,
}
export interface SpendingLimitView {
  'lastMonthReset' : bigint,
  'monthlyLimit' : [] | [bigint],
  'lastWeekReset' : bigint,
  'monthlySpent' : bigint,
  'lastDayReset' : bigint,
  'dailyLimit' : [] | [bigint],
  'dailySpent' : bigint,
  'weeklyLimit' : [] | [bigint],
  'weeklySpent' : bigint,
}
export interface SplitParticipant {
  'status' : SplitParticipantStatus,
  'principal' : Principal,
  'nickname' : string,
  'amount' : bigint,
}
export type SplitParticipantStatus = { 'Paid' : null } |
  { 'Accepted' : null } |
  { 'Declined' : null } |
  { 'Pending' : null };
export interface SplitPayment {
  'id' : string,
  'status' : SplitPaymentStatus,
  'participants' : Array<SplitParticipant>,
  'initiator' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'totalAmount' : bigint,
  'settledAt' : [] | [bigint],
}
export type SplitPaymentStatus = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Settled' : null };
export interface StaffInvite {
  'status' : StaffInviteStatus,
  'method' : StaffInviteMethod,
  'expiresAt' : bigint,
  'inviteePrincipal' : [] | [Principal],
  'createdAt' : bigint,
  'inviteCode' : string,
  'managerPrincipal' : Principal,
}
export type StaffInviteMethod = { 'link' : null } |
  { 'phone' : null };
export type StaffInviteStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface StaffMember {
  'status' : StaffMemberStatus,
  'principal' : Principal,
  'joinedAt' : bigint,
}
export type StaffMemberStatus = { 'active' : null } |
  { 'removed' : null };
export interface Status {
  'customStatus' : [] | [string],
  'createdAt' : bigint,
  'tableNumber' : [] | [bigint],
  'isActive' : boolean,
  'statusType' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportConversation {
  'id' : bigint,
  'status' : SupportStatus,
  'lastMessageAt' : bigint,
  'subject' : string,
  'createdAt' : bigint,
  'userPrincipal' : Principal,
}
export interface SupportMessage {
  'id' : bigint,
  'read' : boolean,
  'conversationId' : bigint,
  'senderPrincipal' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'senderIsAdmin' : boolean,
}
export type SupportStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'waitingForUser' : null };
export type Time = bigint;
export interface Tip {
  'toUser' : Principal,
  'professional' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'fromUser' : Principal,
  'currencyType' : { 'fiat' : null } |
    { 'crypto' : null },
  'amount' : bigint,
}
export interface TipPoolConfig {
  'mode' : TipPoolMode,
  'enabled' : boolean,
  'customSplits' : Array<[Principal, bigint]>,
}
export type TipPoolMode = { 'custom' : null } |
  { 'equal' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TwoFactorSettings {
  'method' : [] | [string],
  'backupCodes' : Array<string>,
  'enabled' : boolean,
}
export interface UserProfile {
  'bio' : string,
  'kycProviderReference' : [] | [string],
  'username' : string,
  'kycSubmissionTimestamp' : [] | [bigint],
  'walletAddress' : [] | [string],
  'email' : string,
  'kycStatus' : KYCStatus,
  'isVerified' : boolean,
  'isFirstWalletConnection' : boolean,
  'photo' : [] | [ExternalBlob],
  'phoneNumber' : [] | [string],
  'currentStatus' : [] | [Status],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VaultStatus {
  'unlockPending' : boolean,
  'locked' : boolean,
  'hoursRemaining' : [] | [number],
  'shouldShowAlert' : boolean,
}
export interface VoicePrintData {
  'voicePrintHash' : string,
  'lastVerified' : [] | [bigint],
  'enrollmentDate' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  /**
   * / Staff: accept a roster invite (link-based or phone-based)
   */
  'acceptStaffInvite' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'acknowledgeVaultAlert' : ActorMethod<[], undefined>,
  'addActiveSession' : ActorMethod<[ActiveSession], undefined>,
  'addPaymentMethod' : ActorMethod<[PaymentMethod], undefined>,
  'addStatus' : ActorMethod<[Status], undefined>,
  'adminCloseSupportTicket' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllSupportConversations' : ActorMethod<
    [],
    Array<[Principal, SupportConversation]>
  >,
  'adminGetSupportMessages' : ActorMethod<[Principal], Array<SupportMessage>>,
  'adminReplySupportMessage' : ActorMethod<
    [Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveBusinessApplication' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<
    [Principal, { 'admin' : null } | { 'user' : null } | { 'guest' : null }],
    undefined
  >,
  'calculateFee' : ActorMethod<
    [
      { 'atm' : null } |
        { 'creditCard' : null } |
        { 'instantDeposit' : null } |
        { 'foreign' : null } |
        { 'businessReceive' : null },
      bigint,
    ],
    bigint
  >,
  'cancelAccountDeletion' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Cancel a money request as the sender (fromUser).
   * / Only pending requests can be cancelled.
   */
  'cancelMoneyRequest' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'cancelRecurringPayment' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Initiator cancels an active split payment.
   */
  'cancelSplitPayment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'cancelVaultUnlock' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'clearSpendingLimits' : ActorMethod<[], { 'ok' : null }>,
  /**
   * / Admin-only: immediately complete a pending deposit and credit the user's balance.
   */
  'completeDirectDeposit' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createRecurringPayment' : ActorMethod<
    [Principal, bigint, string, RecurringFrequency],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Manager: create a roster invite link (expires 72h, good for up to 50 accepts)
   */
  'createRosterInviteLink' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Create a split-payment session.
   * / participantShares: list of (principal, amountInCents) — amounts must sum to totalAmount.
   */
  'createSplitPayment' : ActorMethod<
    [bigint, string, Array<[Principal, bigint]>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createStripeCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deactivateStatus' : ActorMethod<[], undefined>,
  /**
   * / Staff: decline a roster invite
   */
  'declineStaffInvite' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteUserData' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'deleteVoicePrint' : ActorMethod<[], undefined>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'depositToSavings' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'exportUserData' : ActorMethod<[], string>,
  'finalizeAccountDeletion' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'finalizeVaultUnlock' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Query: find a user by their registered phone number (privacy-protected)
   */
  'findUserByPhone' : ActorMethod<[string], [] | [UserProfile]>,
  'generateInviteCode' : ActorMethod<[], string>,
  'generateSmartReceipt' : ActorMethod<[bigint, bigint], SmartReceipt>,
  'getAIQueryHistory' : ActorMethod<[Principal], Array<AIQuery>>,
  'getAccountDeletionStatus' : ActorMethod<[], DeletionStatus>,
  'getActiveSessions' : ActorMethod<[Principal], Array<ActiveSession>>,
  'getAllBusinessApplications' : ActorMethod<
    [],
    Array<[Principal, BusinessApplication]>
  >,
  'getAllFraudAlerts' : ActorMethod<[], Array<FraudAlert>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllSecurityEvents' : ActorMethod<[], Array<SecurityEvent>>,
  'getAllTips' : ActorMethod<[], Array<Tip>>,
  /**
   * / Returns whether the App Lock PIN feature is enabled for the caller.
   * / Defaults to false if no preference has been stored (feature is OFF by default).
   */
  'getAppLockEnabled' : ActorMethod<[], boolean>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getBiometricSettings' : ActorMethod<[Principal], [] | [BiometricSettings]>,
  'getCallerBusinessApplicationStatus' : ActorMethod<
    [],
    [] | [BusinessApplicationStatus]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompilationStatus' : ActorMethod<[], CompilationStatus>,
  'getCurrentStatus' : ActorMethod<[Principal], [] | [Status]>,
  /**
   * / Returns all direct deposits (pending + completed + failed) for the caller.
   * / Lazy evaluation: any pending deposit whose clearAt <= now is auto-completed first.
   */
  'getDirectDepositHistory' : ActorMethod<[], Array<DirectDeposit>>,
  'getEncryptionLog' : ActorMethod<[Principal], Array<EncryptionEvent>>,
  'getFraudAlerts' : ActorMethod<[Principal], Array<FraudAlert>>,
  'getGDPRAuditLog' : ActorMethod<[], Array<GDPRAuditEvent>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getKYCConfigurationStatus' : ActorMethod<
    [],
    { 'provider' : string, 'configured' : boolean }
  >,
  'getLegalAndPrivacy' : ActorMethod<
    [],
    { 'terms' : string, 'privacy' : string }
  >,
  'getManageMyDataAuditLog' : ActorMethod<[], Array<GDPRAuditEvent>>,
  /**
   * / Manager: get the full roster for the calling manager
   */
  'getManagerRoster' : ActorMethod<[], Array<StaffMember>>,
  'getMyBusinessApplication' : ActorMethod<[], [] | [BusinessApplication]>,
  'getMyDisputes' : ActorMethod<[], Array<Dispute>>,
  'getMyRecurringPayments' : ActorMethod<[], Array<RecurringPayment>>,
  /**
   * / Staff: get all pending invites sent TO the caller
   */
  'getMyRosterInvites' : ActorMethod<[], Array<StaffInvite>>,
  /**
   * / Get or create the caller's virtual direct deposit account.
   * / Routing and account numbers are derived deterministically from the caller's
   * / Principal, so they are stable across calls and canister upgrades.
   */
  'getOrCreateDirectDepositAccount' : ActorMethod<[], DirectDepositAccount>,
  'getPaymentMethods' : ActorMethod<[Principal], Array<PaymentMethod>>,
  /**
   * / Manager: get full payout history
   */
  'getPayoutHistory' : ActorMethod<[], Array<PayoutRecord>>,
  'getPendingBusinessApplications' : ActorMethod<
    [],
    Array<[Principal, BusinessApplication]>
  >,
  /**
   * / Returns all pending direct deposits for the caller.
   */
  'getPendingDirectDeposits' : ActorMethod<[], Array<DirectDeposit>>,
  /**
   * / Returns only PENDING money requests addressed to the caller, newest first.
   */
  'getPendingRequestsReceived' : ActorMethod<[], Array<MoneyRequest>>,
  'getProfessionalTips' : ActorMethod<[Principal], Array<Tip>>,
  'getPublicCurrentStatus' : ActorMethod<[Principal], [] | [Status]>,
  'getPublicProfile' : ActorMethod<
    [string],
    [] | [
      {
        'bio' : string,
        'username' : string,
        'isVerified' : boolean,
        'photo' : [] | [ExternalBlob],
        'currentStatus' : [] | [Status],
      }
    ]
  >,
  'getPublicProfileByPrincipal' : ActorMethod<
    [Principal],
    [] | [
      {
        'bio' : string,
        'username' : string,
        'isVerified' : boolean,
        'photo' : [] | [ExternalBlob],
        'currentStatus' : [] | [Status],
      }
    ]
  >,
  /**
   * / Returns all money requests sent TO the caller, newest first.
   */
  'getRequestsReceived' : ActorMethod<[], Array<MoneyRequest>>,
  /**
   * / Returns all money requests sent BY the caller, newest first.
   */
  'getRequestsSent' : ActorMethod<[], Array<MoneyRequest>>,
  'getSMSConfigurationStatus' : ActorMethod<[], boolean>,
  'getSavingsBalance' : ActorMethod<[], bigint>,
  'getSavingsHistory' : ActorMethod<[], Array<SavingsTransaction>>,
  'getSecurityEvents' : ActorMethod<[Principal], Array<SecurityEvent>>,
  'getSmartReceipt' : ActorMethod<
    [Principal, bigint, bigint],
    [] | [SmartReceipt]
  >,
  'getSpendingLimits' : ActorMethod<[], [] | [SpendingLimitView]>,
  /**
   * / Returns a single split payment by ID (only if caller is initiator or participant).
   */
  'getSplitById' : ActorMethod<[string], [] | [SplitPayment]>,
  /**
   * / Returns all split payments where caller is the initiator or a participant.
   */
  'getSplitPayments' : ActorMethod<[], Array<SplitPayment>>,
  /**
   * / Manager: get summed tips received per staff member since an optional timestamp, sorted descending
   */
  'getStaffTipTotals' : ActorMethod<
    [[] | [bigint]],
    Array<[Principal, bigint]>
  >,
  'getStatuses' : ActorMethod<[Principal], Array<Status>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportConversation' : ActorMethod<[], [] | [SupportConversation]>,
  'getSupportMessages' : ActorMethod<[], Array<SupportMessage>>,
  /**
   * / Manager: get current tip pool settings
   */
  'getTipPoolSettings' : ActorMethod<[], TipPoolConfig>,
  'getTips' : ActorMethod<[], Array<Tip>>,
  'getTipsReceived' : ActorMethod<[Principal], Array<Tip>>,
  'getTipsSent' : ActorMethod<[Principal], Array<Tip>>,
  'getTwoFactorSettings' : ActorMethod<[Principal], [] | [TwoFactorSettings]>,
  'getUnreadSupportCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVaultStatus' : ActorMethod<[], VaultStatus>,
  'getVoicePrint' : ActorMethod<[Principal], [] | [VoicePrintData]>,
  'hasExistingPin' : ActorMethod<[], boolean>,
  /**
   * / Manager: invite a staff member by their phone number
   */
  'inviteStaffByPhone' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isKYCConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'lockVault' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'logAIQuery' : ActorMethod<[string, string], undefined>,
  'logEncryptionEvent' : ActorMethod<[EncryptionEvent], undefined>,
  'logSecurityEvent' : ActorMethod<[SecurityEvent], undefined>,
  'logoutSession' : ActorMethod<[string], undefined>,
  'markSupportMessagesRead' : ActorMethod<[], undefined>,
  'markTutorialCompleted' : ActorMethod<[], undefined>,
  'openSupportTicket' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: execute all due recurring payments.
   */
  'processRecurringPayments' : ActorMethod<[], undefined>,
  'recordDisputeRequest' : ActorMethod<
    [bigint, Principal, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordExportRequest' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Manager: record a payout distribution (does NOT move funds — manager controls external settlement)
   */
  'recordPayout' : ActorMethod<
    [Array<[Principal, bigint]>, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'rejectBusinessApplication' : ActorMethod<
    [Principal, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeActiveSession' : ActorMethod<[string], undefined>,
  'removePaymentMethod' : ActorMethod<[string], undefined>,
  /**
   * / Manager: remove a staff member from the roster
   */
  'removeStaffMember' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeStatus' : ActorMethod<[bigint], undefined>,
  'removeWalletAddress' : ActorMethod<[], undefined>,
  'reportFraudAlert' : ActorMethod<[FraudAlert], undefined>,
  'requestAccountDeletion' : ActorMethod<
    [],
    {
        'ok' : {
          'scheduledDeletionTime' : bigint,
          'confirmationToken' : string,
        }
      } |
      { 'err' : string }
  >,
  /**
   * / Create a money request to another user.
   * / A message is REQUIRED — callers cannot request money without explaining what it's for.
   */
  'requestMoney' : ActorMethod<
    [Principal, bigint, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'requestVaultUnlock' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resolveDispute' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resolveFraudAlert' : ActorMethod<[Principal, bigint], undefined>,
  /**
   * / Resolve a user Principal by their username or phone number.
   * / Returns the Principal of the matching user, or null if not found.
   * / Used by the split-payment UI to look up real Principals during participant search.
   */
  'resolveUserByUsername' : ActorMethod<[string], [] | [Principal]>,
  /**
   * / Respond to a money request as the recipient (toUser).
   * / accept=true: deducts from caller's balance, credits requester, creates a tip record.
   * / accept=false: marks the request as declined.
   */
  'respondToMoneyRequest' : ActorMethod<
    [bigint, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Respond to a split payment — participant accepts or declines their share.
   * / On decline: participant's status → #Declined, whole split → #Cancelled, initiator notified.
   * / On accept: participant's status → #Accepted; if ALL accepted, payments are settled immediately.
   */
  'respondToSplitPayment' : ActorMethod<
    [string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveVoicePrint' : ActorMethod<[VoicePrintData], undefined>,
  'saveWalletAddress' : ActorMethod<
    [string],
    { 'error' : string } |
      { 'success' : boolean }
  >,
  'searchUsers' : ActorMethod<[string], Array<SearchResult>>,
  'sendSupportMessage' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'sendTip' : ActorMethod<
    [
      Principal,
      bigint,
      string,
      boolean,
      { 'fiat' : null } |
        { 'crypto' : null },
    ],
    undefined
  >,
  'sendTipWithFee' : ActorMethod<
    [
      Principal,
      bigint,
      string,
      boolean,
      { 'fiat' : null } |
        { 'crypto' : null },
      string,
    ],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  /**
   * / Enables or disables the App Lock PIN feature for the caller.
   * / When disabling, the stored PIN data is cleared so a fresh PIN must be
   * / set if the feature is re-enabled later.
   */
  'setAppLockEnabled' : ActorMethod<[boolean], undefined>,
  'setBiometricSettings' : ActorMethod<[BiometricSettings], undefined>,
  'setKYCConfiguration' : ActorMethod<[string, string], undefined>,
  'setKYCStatus' : ActorMethod<
    [Principal, KYCStatus, [] | [string]],
    undefined
  >,
  'setPinHash' : ActorMethod<[Uint8Array, Uint8Array], undefined>,
  'setSMSConfiguration' : ActorMethod<[string, string, string], undefined>,
  'setSpendingLimits' : ActorMethod<
    [[] | [bigint], [] | [bigint], [] | [bigint]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  /**
   * / Manager: enable/disable tip pooling and set distribution mode
   */
  'setTipPoolMode' : ActorMethod<
    [boolean, TipPoolMode],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTwoFactorSettings' : ActorMethod<[TwoFactorSettings], undefined>,
  'setUserVerificationStatus' : ActorMethod<[Principal, boolean], undefined>,
  /**
   * / Admin-only: simulate an incoming direct deposit for a target user.
   * / Creates a pending deposit with clearAt set ~2 business days (48h) in the future.
   */
  'simulateDirectDeposit' : ActorMethod<
    [Principal, bigint, string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'startWithdrawalOTPChallenge' : ActorMethod<
    [bigint],
    {
        'ok' : {
          'expiresIn' : bigint,
          'challengeId' : string,
          'phoneSuffix' : string,
        }
      } |
      { 'err' : string }
  >,
  'submitBusinessApplication' : ActorMethod<
    [string, string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitKYC' : ActorMethod<[], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'toggleRecurringPayment' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePaymentMethodVerificationStatus' : ActorMethod<
    [string, string],
    undefined
  >,
  'verifyPinHash' : ActorMethod<[Uint8Array, Uint8Array], PinCheckResult>,
  'verifyWithdrawalOTP' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'withdraw' : ActorMethod<[bigint, [] | [string]], undefined>,
  'withdrawFromSavings' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'withdrawWithFee' : ActorMethod<
    [bigint, [] | [string], string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];