/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ActiveSession = IDL.Record({
  'loginTimestamp' : IDL.Int,
  'deviceName' : IDL.Text,
  'sessionId' : IDL.Text,
  'location' : IDL.Text,
});
export const CentAmount = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'standId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'priceInCents' : CentAmount,
});
export const PaymentMethodType = IDL.Variant({
  'bankAccount' : IDL.Null,
  'card' : IDL.Null,
});
export const PaymentMethod = IDL.Record({
  'id' : IDL.Text,
  'methodType' : PaymentMethodType,
  'last4' : IDL.Text,
  'bankName' : IDL.Opt(IDL.Text),
  'accountType' : IDL.Opt(IDL.Text),
  'addedAt' : IDL.Int,
  'stripeVerificationStatus' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Record({
  'customStatus' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'tableNumber' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
  'statusType' : IDL.Text,
});
export const SupportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'waitingForUser' : IDL.Null,
});
export const SupportConversation = IDL.Record({
  'id' : IDL.Nat,
  'status' : SupportStatus,
  'lastMessageAt' : IDL.Int,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'userPrincipal' : IDL.Principal,
});
export const SupportMessage = IDL.Record({
  'id' : IDL.Nat,
  'read' : IDL.Bool,
  'conversationId' : IDL.Nat,
  'senderPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderIsAdmin' : IDL.Bool,
});
export const TipSplitCalculation = IDL.Record({
  'staffName' : IDL.Text,
  'staffId' : IDL.Text,
  'hoursWorked' : IDL.Float64,
  'role' : IDL.Text,
  'sharePercent' : IDL.Float64,
  'weightedScore' : IDL.Float64,
  'rolePoints' : IDL.Float64,
  'payoutAmount' : IDL.Float64,
});
export const TipSplitPayout = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'standName' : IDL.Text,
  'standId' : IDL.Text,
  'approvedAt' : IDL.Opt(IDL.Int),
  'approvedBy' : IDL.Opt(IDL.Text),
  'totalPool' : IDL.Float64,
  'calculations' : IDL.Vec(TipSplitCalculation),
  'gameDate' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffSection = IDL.Record({
  'assignedAt' : IDL.Int,
  'staffId' : IDL.Principal,
  'sectionName' : IDL.Text,
  'managerId' : IDL.Principal,
  'sectionLabel' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PointsRuleType = IDL.Variant({
  'paymentMultiplier' : IDL.Null,
  'firstPaymentBonus' : IDL.Null,
  'foodMultiplier' : IDL.Null,
  'sectionMultiplier' : IDL.Null,
  'tipMultiplier' : IDL.Null,
  'gameDayBonus' : IDL.Null,
});
export const PointsRule = IDL.Record({
  'id' : IDL.Text,
  'multiplier' : IDL.Float64,
  'ruleType' : PointsRuleType,
  'sectionName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const RecurringFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const RewardType = IDL.Variant({
  'other' : IDL.Null,
  'discountCode' : IDL.Null,
  'concessionCredit' : IDL.Null,
  'ticketEntry' : IDL.Null,
});
export const Reward = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'expiresAt' : IDL.Opt(IDL.Int),
  'quantityRemaining' : IDL.Opt(IDL.Nat),
  'createdBy' : IDL.Principal,
  'codeOrValue' : IDL.Text,
  'description' : IDL.Text,
  'rewardType' : RewardType,
  'quantity' : IDL.Opt(IDL.Nat),
  'pointsCost' : IDL.Nat,
  'teamId' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const ConcessionStand = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'section' : IDL.Text,
  'description' : IDL.Text,
});
export const KYCStatus = IDL.Variant({
  'notSubmitted' : IDL.Null,
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'kycProviderReference' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'kycSubmissionTimestamp' : IDL.Opt(IDL.Int),
  'walletAddress' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'kycStatus' : KYCStatus,
  'isVerified' : IDL.Bool,
  'isFirstWalletConnection' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Opt(IDL.Text),
  'currentStatus' : IDL.Opt(Status),
});
export const Tip = IDL.Record({
  'toUser' : IDL.Principal,
  'professional' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'fromUser' : IDL.Principal,
  'currencyType' : IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
  'amount' : IDL.Nat,
});
export const SmartReceipt = IDL.Record({
  'month' : IDL.Nat,
  'userId' : IDL.Principal,
  'generatedAt' : IDL.Int,
  'professionalTips' : IDL.Vec(Tip),
  'year' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const AIQuery = IDL.Record({
  'queryText' : IDL.Text,
  'userId' : IDL.Principal,
  'response' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DeletionStatus = IDL.Variant({
  'pending' : IDL.Record({ 'scheduledDeletionTime' : IDL.Int }),
  'not_requested' : IDL.Null,
  'finalized' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'OnTheWay' : IDL.Null,
  'Placed' : IDL.Null,
  'ReadyForPickup' : IDL.Null,
  'Preparing' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const DeliveryMethod = IDL.Variant({
  'Delivery' : IDL.Null,
  'Pickup' : IDL.Null,
});
export const UserId = IDL.Principal;
export const OrderItem = IDL.Record({
  'itemId' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : CentAmount,
});
export const FoodOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'standId' : IDL.Text,
  'createdAt' : Timestamp,
  'deliveryMethod' : DeliveryMethod,
  'updatedAt' : Timestamp,
  'totalInCents' : CentAmount,
  'customerId' : UserId,
  'items' : IDL.Vec(OrderItem),
  'seatNumber' : IDL.Text,
});
export const BusinessApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BusinessApplication = IDL.Record({
  'status' : BusinessApplicationStatus,
  'termsAccepted' : IDL.Bool,
  'createdAt' : IDL.Int,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const FraudAlert = IDL.Record({
  'resolved' : IDL.Bool,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'severity' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'reason' : IDL.Text,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const SecurityEvent = IDL.Record({
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'eventType' : IDL.Text,
});
export const BiometricSettings = IDL.Record({
  'biometricType' : IDL.Opt(IDL.Text),
  'enabled' : IDL.Bool,
});
export const StaffCheckIn = IDL.Record({
  'id' : IDL.Text,
  'staffName' : IDL.Text,
  'staffId' : IDL.Text,
  'standName' : IDL.Text,
  'standId' : IDL.Text,
  'hoursWorked' : IDL.Opt(IDL.Float64),
  'role' : IDL.Text,
  'checkInTime' : IDL.Int,
  'manualOverride' : IDL.Bool,
  'gameDate' : IDL.Text,
  'checkOutTime' : IDL.Opt(IDL.Int),
  'overrideBy' : IDL.Opt(IDL.Text),
});
export const CompilationStatus = IDL.Record({
  'obfuscationLayer' : IDL.Text,
  'verificationTimestamp' : IDL.Int,
  'tooltipNote' : IDL.Text,
});
export const DirectDeposit = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isTest' : IDL.Bool,
  'userPrincipal' : IDL.Principal,
  'clearAt' : IDL.Int,
  'amount' : IDL.Nat,
});
export const EncryptionEvent = IDL.Record({
  'dataType' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});
export const ExtendedStaffMember = IDL.Record({
  'id' : IDL.Text,
  'hireDate' : IDL.Int,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : IDL.Variant({
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
    'contractor' : IDL.Null,
  }),
  'notes' : IDL.Text,
  'customRole' : IDL.Text,
  'phone' : IDL.Text,
  'employmentStatus' : IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'suspended' : IDL.Null,
  }),
});
export const FanPoints = IDL.Record({
  'userId' : IDL.Principal,
  'totalEarned' : IDL.Float64,
  'totalRedeemed' : IDL.Float64,
  'guestContact' : IDL.Opt(IDL.Text),
  'points' : IDL.Float64,
});
export const GDPRAuditEventType = IDL.Variant({
  'deletion_finalized' : IDL.Null,
  'deletion_requested' : IDL.Null,
  'deletion_cancelled' : IDL.Null,
  'export_requested' : IDL.Null,
});
export const GDPRAuditEvent = IDL.Record({
  'principal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'eventType' : GDPRAuditEventType,
});
export const GameStandAssignment = IDL.Record({
  'id' : IDL.Text,
  'gameStandId' : IDL.Text,
  'staffName' : IDL.Text,
  'staffId' : IDL.Text,
  'defaultStandId' : IDL.Text,
  'gameStandName' : IDL.Text,
  'gameDate' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const StaffMemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'removed' : IDL.Null,
});
export const StaffMember = IDL.Record({
  'status' : StaffMemberStatus,
  'principal' : IDL.Principal,
  'joinedAt' : IDL.Int,
});
export const DisputeStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Dispute = IDL.Record({
  'id' : IDL.Text,
  'status' : DisputeStatus,
  'submitterPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'resolution' : IDL.Opt(IDL.Text),
  'transactionTimestamp' : IDL.Int,
  'updatedAt' : IDL.Int,
  'counterpartyPrincipal' : IDL.Principal,
  'reason' : IDL.Text,
});
export const RecurringPayment = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'lastRunAt' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'totalRuns' : IDL.Nat,
  'enabled' : IDL.Bool,
  'toUser' : IDL.Principal,
  'message' : IDL.Text,
  'nextRunTime' : IDL.Int,
  'frequency' : RecurringFrequency,
  'amount' : IDL.Nat,
});
export const RedeemedReward = IDL.Record({
  'id' : IDL.Text,
  'redeemedAt' : IDL.Int,
  'rewardTitle' : IDL.Text,
  'userId' : IDL.Principal,
  'codeOrValue' : IDL.Text,
  'rewardId' : IDL.Text,
  'contactEmail' : IDL.Opt(IDL.Text),
  'emailSent' : IDL.Bool,
});
export const StaffInviteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const StaffInviteMethod = IDL.Variant({
  'link' : IDL.Null,
  'phone' : IDL.Null,
});
export const StaffInvite = IDL.Record({
  'status' : StaffInviteStatus,
  'method' : StaffInviteMethod,
  'expiresAt' : IDL.Int,
  'inviteePrincipal' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'inviteCode' : IDL.Text,
  'managerPrincipal' : IDL.Principal,
});
export const DirectDepositAccount = IDL.Record({
  'status' : IDL.Text,
  'routingNumber' : IDL.Text,
  'createdAt' : IDL.Int,
  'accountNumber' : IDL.Text,
});
export const PartnerBrandingConfig = IDL.Record({
  'partnerName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'isActive' : IDL.Bool,
  'secondaryColor' : IDL.Text,
  'partnerLogoUrl' : IDL.Text,
});
export const PayoutRecord = IDL.Record({
  'id' : IDL.Text,
  'distributions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'managerPrincipal' : IDL.Principal,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'declined' : IDL.Null,
});
export const MoneyRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'toUser' : IDL.Principal,
  'message' : IDL.Text,
  'paidTipId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'fromUser' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const PointsBreakdown = IDL.Record({
  'transactionType' : IDL.Text,
  'finalPoints' : IDL.Float64,
  'amountCents' : IDL.Nat,
  'appliedRules' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Opt(IDL.Text))),
  'basePoints' : IDL.Float64,
});
export const SavingsDirection = IDL.Variant({
  'fromSavings' : IDL.Null,
  'toSavings' : IDL.Null,
});
export const SavingsTransaction = IDL.Record({
  'id' : IDL.Nat,
  'direction' : SavingsDirection,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const SectionAnalytics = IDL.Record({
  'sectionName' : IDL.Text,
  'totalTips' : IDL.Nat,
  'topStaffId' : IDL.Opt(IDL.Principal),
  'totalAmount' : IDL.Nat,
  'sectionLabel' : IDL.Text,
  'staffCount' : IDL.Nat,
});
export const SpendingLimitView = IDL.Record({
  'lastMonthReset' : IDL.Int,
  'monthlyLimit' : IDL.Opt(IDL.Nat),
  'lastWeekReset' : IDL.Int,
  'monthlySpent' : IDL.Nat,
  'lastDayReset' : IDL.Int,
  'dailyLimit' : IDL.Opt(IDL.Nat),
  'dailySpent' : IDL.Nat,
  'weeklyLimit' : IDL.Opt(IDL.Nat),
  'weeklySpent' : IDL.Nat,
});
export const SplitPaymentStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Settled' : IDL.Null,
});
export const SplitParticipantStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Accepted' : IDL.Null,
  'Declined' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SplitParticipant = IDL.Record({
  'status' : SplitParticipantStatus,
  'principal' : IDL.Principal,
  'nickname' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SplitPayment = IDL.Record({
  'id' : IDL.Text,
  'status' : SplitPaymentStatus,
  'participants' : IDL.Vec(SplitParticipant),
  'initiator' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'settledAt' : IDL.Opt(IDL.Int),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TipPoolMode = IDL.Variant({
  'custom' : IDL.Null,
  'equal' : IDL.Null,
});
export const TipPoolConfig = IDL.Record({
  'mode' : TipPoolMode,
  'enabled' : IDL.Bool,
  'customSplits' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
});
export const TipSplitRole = IDL.Record({
  'id' : IDL.Text,
  'roleName' : IDL.Text,
  'pointValue' : IDL.Float64,
  'isCustom' : IDL.Bool,
});
export const TwoFactorSettings = IDL.Record({
  'method' : IDL.Opt(IDL.Text),
  'backupCodes' : IDL.Vec(IDL.Text),
  'enabled' : IDL.Bool,
});
export const VaultStatus = IDL.Record({
  'unlockPending' : IDL.Bool,
  'locked' : IDL.Bool,
  'hoursRemaining' : IDL.Opt(IDL.Float64),
  'shouldShowAlert' : IDL.Bool,
});
export const VoicePrintData = IDL.Record({
  'voicePrintHash' : IDL.Text,
  'lastVerified' : IDL.Opt(IDL.Int),
  'enrollmentDate' : IDL.Int,
});
export const OrderItemInput = IDL.Record({
  'itemId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const SearchResult = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'isVerified' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateRewardParams = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'active' : IDL.Opt(IDL.Bool),
  'codeOrValue' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Opt(IDL.Nat),
  'pointsCost' : IDL.Opt(IDL.Nat),
  'teamId' : IDL.Opt(IDL.Text),
});
export const PinCheckResult = IDL.Variant({
  'verified' : IDL.Null,
  'blocked' : IDL.Nat,
  'incorrect' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptStaffInvite' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'acknowledgeVaultAlert' : IDL.Func([], [], []),
  'addActiveSession' : IDL.Func([ActiveSession], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text })],
      [],
    ),
  'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
  'addStatus' : IDL.Func([Status], [], []),
  'adminCloseSupportTicket' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllSupportConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SupportConversation))],
      ['query'],
    ),
  'adminGetSupportMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SupportMessage)],
      ['query'],
    ),
  'adminReplySupportMessage' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveBusinessApplication' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveTipSplitPayout' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : TipSplitPayout, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignStaffSection' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : StaffSection, 'err' : IDL.Text })],
      [],
    ),
  'assignUserRole' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({
          'admin' : IDL.Null,
          'user' : IDL.Null,
          'guest' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'calculateFee' : IDL.Func(
      [
        IDL.Variant({
          'atm' : IDL.Null,
          'creditCard' : IDL.Null,
          'instantDeposit' : IDL.Null,
          'foreign' : IDL.Null,
          'businessReceive' : IDL.Null,
        }),
        IDL.Nat,
      ],
      [IDL.Nat],
      ['query'],
    ),
  'calculateTipSplit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : TipSplitPayout, 'err' : IDL.Text })],
      [],
    ),
  'cancelAccountDeletion' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelMoneyRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'cancelOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelRecurringPayment' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelSplitPayment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'cancelVaultUnlock' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'clearPartnerBranding' : IDL.Func([], [], []),
  'clearSpendingLimits' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
  'completeDirectDeposit' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPointsRule' : IDL.Func(
      [PointsRule],
      [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
      [],
    ),
  'createRecurringPayment' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, RecurringFrequency],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createReward' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        RewardType,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Reward, 'err' : IDL.Text })],
      [],
    ),
  'createRosterInviteLink' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createSplitPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createStand' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ConcessionStand, 'err' : IDL.Text })],
      [],
    ),
  'createStripeCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateStatus' : IDL.Func([], [], []),
  'declineStaffInvite' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMenuItem' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReward' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteStand' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUserData' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteVoicePrint' : IDL.Func([], [], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'depositToSavings' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'exportUserData' : IDL.Func([], [IDL.Text], ['query']),
  'finalizeAccountDeletion' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'finalizeVaultUnlock' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'findUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'generateSmartReceipt' : IDL.Func([IDL.Nat, IDL.Nat], [SmartReceipt], []),
  'getAIQueryHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AIQuery)],
      ['query'],
    ),
  'getAccountDeletionStatus' : IDL.Func([], [DeletionStatus], ['query']),
  'getActiveOrdersForManager' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
  'getActiveSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActiveSession)],
      ['query'],
    ),
  'getAllBusinessApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessApplication))],
      ['query'],
    ),
  'getAllFraudAlerts' : IDL.Func([], [IDL.Vec(FraudAlert)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
  'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getAppLockEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getBiometricSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BiometricSettings)],
      ['query'],
    ),
  'getCallerBusinessApplicationStatus' : IDL.Func(
      [],
      [IDL.Opt(BusinessApplicationStatus)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInsForGame' : IDL.Func([IDL.Text], [IDL.Vec(StaffCheckIn)], []),
  'getCompilationStatus' : IDL.Func([], [CompilationStatus], ['query']),
  'getCurrentStatus' : IDL.Func([IDL.Principal], [IDL.Opt(Status)], ['query']),
  'getDirectDepositHistory' : IDL.Func([], [IDL.Vec(DirectDeposit)], []),
  'getEncryptionLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EncryptionEvent)],
      ['query'],
    ),
  'getExtendedStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExtendedStaffMember)],
      ['query'],
    ),
  'getFanPoints' : IDL.Func([IDL.Principal], [IDL.Opt(FanPoints)], ['query']),
  'getFraudAlerts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FraudAlert)],
      ['query'],
    ),
  'getGDPRAuditLog' : IDL.Func([], [IDL.Vec(GDPRAuditEvent)], ['query']),
  'getGameStandAssignment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(GameStandAssignment)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getKYCConfigurationStatus' : IDL.Func(
      [],
      [IDL.Record({ 'provider' : IDL.Text, 'configured' : IDL.Bool })],
      ['query'],
    ),
  'getLegalAndPrivacy' : IDL.Func(
      [],
      [IDL.Record({ 'terms' : IDL.Text, 'privacy' : IDL.Text })],
      ['query'],
    ),
  'getManageMyDataAuditLog' : IDL.Func(
      [],
      [IDL.Vec(GDPRAuditEvent)],
      ['query'],
    ),
  'getManagerRoster' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getMyBusinessApplication' : IDL.Func(
      [],
      [IDL.Opt(BusinessApplication)],
      ['query'],
    ),
  'getMyDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
  'getMyFanPoints' : IDL.Func([], [IDL.Opt(FanPoints)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
  'getMyRecurringPayments' : IDL.Func(
      [],
      [IDL.Vec(RecurringPayment)],
      ['query'],
    ),
  'getMyRedeemedRewards' : IDL.Func([], [IDL.Vec(RedeemedReward)], ['query']),
  'getMyRosterInvites' : IDL.Func([], [IDL.Vec(StaffInvite)], ['query']),
  'getOrCreateDirectDepositAccount' : IDL.Func([], [DirectDepositAccount], []),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(FoodOrder)], ['query']),
  'getPartnerBranding' : IDL.Func(
      [],
      [IDL.Opt(PartnerBrandingConfig)],
      ['query'],
    ),
  'getPaymentMethods' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getPendingBusinessApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessApplication))],
      ['query'],
    ),
  'getPendingDirectDeposits' : IDL.Func(
      [],
      [IDL.Vec(DirectDeposit)],
      ['query'],
    ),
  'getPendingRequestsReceived' : IDL.Func(
      [],
      [IDL.Vec(MoneyRequest)],
      ['query'],
    ),
  'getPointsBreakdown' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
      [PointsBreakdown],
      ['query'],
    ),
  'getProfessionalTips' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
  'getPublicCurrentStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Status)],
      ['query'],
    ),
  'getPublicProfile' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'bio' : IDL.Text,
            'username' : IDL.Text,
            'isVerified' : IDL.Bool,
            'photo' : IDL.Opt(ExternalBlob),
            'currentStatus' : IDL.Opt(Status),
          })
        ),
      ],
      ['query'],
    ),
  'getPublicProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'bio' : IDL.Text,
            'username' : IDL.Text,
            'isVerified' : IDL.Bool,
            'photo' : IDL.Opt(ExternalBlob),
            'currentStatus' : IDL.Opt(Status),
          })
        ),
      ],
      ['query'],
    ),
  'getRequestsReceived' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
  'getRequestsSent' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
  'getReward' : IDL.Func([IDL.Text], [IDL.Opt(Reward)], ['query']),
  'getSMSConfigurationStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getSavingsBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getSavingsHistory' : IDL.Func([], [IDL.Vec(SavingsTransaction)], ['query']),
  'getSectionAnalytics' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Int)],
      [IDL.Vec(SectionAnalytics)],
      ['query'],
    ),
  'getSectionAssignments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StaffSection)],
      ['query'],
    ),
  'getSecurityEvents' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SecurityEvent)],
      ['query'],
    ),
  'getSmartReceipt' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Opt(SmartReceipt)],
      ['query'],
    ),
  'getSpendingLimits' : IDL.Func([], [IDL.Opt(SpendingLimitView)], ['query']),
  'getSplitById' : IDL.Func([IDL.Text], [IDL.Opt(SplitPayment)], ['query']),
  'getSplitPayments' : IDL.Func([], [IDL.Vec(SplitPayment)], ['query']),
  'getStaffAnalytics' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Int)],
      [
        IDL.Vec(
          IDL.Record({
            'staffId' : IDL.Principal,
            'sectionName' : IDL.Opt(IDL.Text),
            'totalTips' : IDL.Nat,
            'totalAmount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getStaffSection' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StaffSection)],
      ['query'],
    ),
  'getStaffTipTotals' : IDL.Func(
      [IDL.Opt(IDL.Int)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getStatuses' : IDL.Func([IDL.Principal], [IDL.Vec(Status)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportConversation' : IDL.Func(
      [],
      [IDL.Opt(SupportConversation)],
      ['query'],
    ),
  'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
  'getTipPoolSettings' : IDL.Func([], [TipPoolConfig], ['query']),
  'getTipSplitPayouts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(TipSplitPayout)],
      [],
    ),
  'getTipSplitRoles' : IDL.Func([], [IDL.Vec(TipSplitRole)], ['query']),
  'getTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getTipsReceived' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
  'getTipsSent' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
  'getTwoFactorSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TwoFactorSettings)],
      ['query'],
    ),
  'getUnreadSupportCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVaultStatus' : IDL.Func([], [VaultStatus], ['query']),
  'getVoicePrint' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VoicePrintData)],
      ['query'],
    ),
  'hasExistingPin' : IDL.Func([], [IDL.Bool], ['query']),
  'inviteStaffByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isKYCConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'linkGuestPaymentsToUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'listExtendedStaff' : IDL.Func([], [IDL.Vec(ExtendedStaffMember)], []),
  'listMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'listPointsRules' : IDL.Func([], [IDL.Vec(PointsRule)], ['query']),
  'listRewards' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Reward)], ['query']),
  'listStands' : IDL.Func([], [IDL.Vec(ConcessionStand)], ['query']),
  'lockVault' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'logAIQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'logEncryptionEvent' : IDL.Func([EncryptionEvent], [], []),
  'logSecurityEvent' : IDL.Func([SecurityEvent], [], []),
  'logoutSession' : IDL.Func([IDL.Text], [], []),
  'manualSetHours' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
      [],
    ),
  'markSupportMessagesRead' : IDL.Func([], [], []),
  'markTutorialCompleted' : IDL.Func([], [], []),
  'openSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItemInput), IDL.Text, DeliveryMethod],
      [IDL.Variant({ 'ok' : FoodOrder, 'err' : IDL.Text })],
      [],
    ),
  'processRecurringPayments' : IDL.Func([], [], []),
  'recordCheckIn' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
      [],
    ),
  'recordCheckOut' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
      [],
    ),
  'recordDisputeRequest' : IDL.Func(
      [IDL.Int, IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordExportRequest' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordGuestPayment' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        IDL.Text,
        IDL.Variant({ 'email' : IDL.Null, 'phone' : IDL.Null }),
        IDL.Opt(IDL.Text),
      ],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'guestRecordId' : IDL.Text,
            'fanPointsAwarded' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'recordPayout' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'redeemReward' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : RedeemedReward, 'err' : IDL.Text })],
      [],
    ),
  'rejectBusinessApplication' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeActiveSession' : IDL.Func([IDL.Text], [], []),
  'removeExtendedStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
  'removeStaffMember' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeStatus' : IDL.Func([IDL.Nat], [], []),
  'removeTipSplitRole' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeWalletAddress' : IDL.Func([], [], []),
  'reportFraudAlert' : IDL.Func([FraudAlert], [], []),
  'requestAccountDeletion' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'scheduledDeletionTime' : IDL.Int,
            'confirmationToken' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'requestMoney' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'requestVaultUnlock' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resolveDispute' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resolveFraudAlert' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'resolveUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'respondToMoneyRequest' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'respondToSplitPayment' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVoicePrint' : IDL.Func([VoicePrintData], [], []),
  'saveWalletAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendSupportMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'sendTip' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
      ],
      [],
      [],
    ),
  'sendTipWithFee' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'setAppLockEnabled' : IDL.Func([IDL.Bool], [], []),
  'setBiometricSettings' : IDL.Func([BiometricSettings], [], []),
  'setGameStandAssignment' : IDL.Func(
      [GameStandAssignment],
      [IDL.Variant({ 'ok' : GameStandAssignment, 'err' : IDL.Text })],
      [],
    ),
  'setKYCConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setKYCStatus' : IDL.Func(
      [IDL.Principal, KYCStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'setPartnerBranding' : IDL.Func([PartnerBrandingConfig], [], []),
  'setPinHash' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)], [], []),
  'setSMSConfiguration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setSpendingLimits' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setTipPoolMode' : IDL.Func(
      [IDL.Bool, TipPoolMode],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setTwoFactorSettings' : IDL.Func([TwoFactorSettings], [], []),
  'setUserVerificationStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'simulateDirectDeposit' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'startWithdrawalOTPChallenge' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'expiresIn' : IDL.Nat,
            'challengeId' : IDL.Text,
            'phoneSuffix' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'submitBusinessApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitKYC' : IDL.Func([], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'togglePointsRule' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
      [],
    ),
  'toggleRecurringPayment' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePaymentMethodVerificationStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePointsRule' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
      [],
    ),
  'updateReward' : IDL.Func(
      [IDL.Text, UpdateRewardParams],
      [IDL.Variant({ 'ok' : Reward, 'err' : IDL.Text })],
      [],
    ),
  'updateStand' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ConcessionStand, 'err' : IDL.Text })],
      [],
    ),
  'upsertExtendedStaff' : IDL.Func(
      [ExtendedStaffMember],
      [IDL.Variant({ 'ok' : ExtendedStaffMember, 'err' : IDL.Text })],
      [],
    ),
  'upsertTipSplitRole' : IDL.Func(
      [TipSplitRole],
      [IDL.Variant({ 'ok' : TipSplitRole, 'err' : IDL.Text })],
      [],
    ),
  'verifyPinHash' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
      [PinCheckResult],
      [],
    ),
  'verifyWithdrawalOTP' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'withdraw' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'withdrawFromSavings' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'withdrawWithFee' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ActiveSession = IDL.Record({
    'loginTimestamp' : IDL.Int,
    'deviceName' : IDL.Text,
    'sessionId' : IDL.Text,
    'location' : IDL.Text,
  });
  const CentAmount = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'standId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'priceInCents' : CentAmount,
  });
  const PaymentMethodType = IDL.Variant({
    'bankAccount' : IDL.Null,
    'card' : IDL.Null,
  });
  const PaymentMethod = IDL.Record({
    'id' : IDL.Text,
    'methodType' : PaymentMethodType,
    'last4' : IDL.Text,
    'bankName' : IDL.Opt(IDL.Text),
    'accountType' : IDL.Opt(IDL.Text),
    'addedAt' : IDL.Int,
    'stripeVerificationStatus' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Record({
    'customStatus' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'tableNumber' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
    'statusType' : IDL.Text,
  });
  const SupportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'waitingForUser' : IDL.Null,
  });
  const SupportConversation = IDL.Record({
    'id' : IDL.Nat,
    'status' : SupportStatus,
    'lastMessageAt' : IDL.Int,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'userPrincipal' : IDL.Principal,
  });
  const SupportMessage = IDL.Record({
    'id' : IDL.Nat,
    'read' : IDL.Bool,
    'conversationId' : IDL.Nat,
    'senderPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderIsAdmin' : IDL.Bool,
  });
  const TipSplitCalculation = IDL.Record({
    'staffName' : IDL.Text,
    'staffId' : IDL.Text,
    'hoursWorked' : IDL.Float64,
    'role' : IDL.Text,
    'sharePercent' : IDL.Float64,
    'weightedScore' : IDL.Float64,
    'rolePoints' : IDL.Float64,
    'payoutAmount' : IDL.Float64,
  });
  const TipSplitPayout = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'standName' : IDL.Text,
    'standId' : IDL.Text,
    'approvedAt' : IDL.Opt(IDL.Int),
    'approvedBy' : IDL.Opt(IDL.Text),
    'totalPool' : IDL.Float64,
    'calculations' : IDL.Vec(TipSplitCalculation),
    'gameDate' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffSection = IDL.Record({
    'assignedAt' : IDL.Int,
    'staffId' : IDL.Principal,
    'sectionName' : IDL.Text,
    'managerId' : IDL.Principal,
    'sectionLabel' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PointsRuleType = IDL.Variant({
    'paymentMultiplier' : IDL.Null,
    'firstPaymentBonus' : IDL.Null,
    'foodMultiplier' : IDL.Null,
    'sectionMultiplier' : IDL.Null,
    'tipMultiplier' : IDL.Null,
    'gameDayBonus' : IDL.Null,
  });
  const PointsRule = IDL.Record({
    'id' : IDL.Text,
    'multiplier' : IDL.Float64,
    'ruleType' : PointsRuleType,
    'sectionName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const RecurringFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const RewardType = IDL.Variant({
    'other' : IDL.Null,
    'discountCode' : IDL.Null,
    'concessionCredit' : IDL.Null,
    'ticketEntry' : IDL.Null,
  });
  const Reward = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'expiresAt' : IDL.Opt(IDL.Int),
    'quantityRemaining' : IDL.Opt(IDL.Nat),
    'createdBy' : IDL.Principal,
    'codeOrValue' : IDL.Text,
    'description' : IDL.Text,
    'rewardType' : RewardType,
    'quantity' : IDL.Opt(IDL.Nat),
    'pointsCost' : IDL.Nat,
    'teamId' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const ConcessionStand = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'section' : IDL.Text,
    'description' : IDL.Text,
  });
  const KYCStatus = IDL.Variant({
    'notSubmitted' : IDL.Null,
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'kycProviderReference' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'kycSubmissionTimestamp' : IDL.Opt(IDL.Int),
    'walletAddress' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'kycStatus' : KYCStatus,
    'isVerified' : IDL.Bool,
    'isFirstWalletConnection' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Opt(IDL.Text),
    'currentStatus' : IDL.Opt(Status),
  });
  const Tip = IDL.Record({
    'toUser' : IDL.Principal,
    'professional' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'fromUser' : IDL.Principal,
    'currencyType' : IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
    'amount' : IDL.Nat,
  });
  const SmartReceipt = IDL.Record({
    'month' : IDL.Nat,
    'userId' : IDL.Principal,
    'generatedAt' : IDL.Int,
    'professionalTips' : IDL.Vec(Tip),
    'year' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const AIQuery = IDL.Record({
    'queryText' : IDL.Text,
    'userId' : IDL.Principal,
    'response' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DeletionStatus = IDL.Variant({
    'pending' : IDL.Record({ 'scheduledDeletionTime' : IDL.Int }),
    'not_requested' : IDL.Null,
    'finalized' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'OnTheWay' : IDL.Null,
    'Placed' : IDL.Null,
    'ReadyForPickup' : IDL.Null,
    'Preparing' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const DeliveryMethod = IDL.Variant({
    'Delivery' : IDL.Null,
    'Pickup' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const OrderItem = IDL.Record({
    'itemId' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : CentAmount,
  });
  const FoodOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'standId' : IDL.Text,
    'createdAt' : Timestamp,
    'deliveryMethod' : DeliveryMethod,
    'updatedAt' : Timestamp,
    'totalInCents' : CentAmount,
    'customerId' : UserId,
    'items' : IDL.Vec(OrderItem),
    'seatNumber' : IDL.Text,
  });
  const BusinessApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BusinessApplication = IDL.Record({
    'status' : BusinessApplicationStatus,
    'termsAccepted' : IDL.Bool,
    'createdAt' : IDL.Int,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const FraudAlert = IDL.Record({
    'resolved' : IDL.Bool,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'severity' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'reason' : IDL.Text,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const SecurityEvent = IDL.Record({
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const BiometricSettings = IDL.Record({
    'biometricType' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
  });
  const StaffCheckIn = IDL.Record({
    'id' : IDL.Text,
    'staffName' : IDL.Text,
    'staffId' : IDL.Text,
    'standName' : IDL.Text,
    'standId' : IDL.Text,
    'hoursWorked' : IDL.Opt(IDL.Float64),
    'role' : IDL.Text,
    'checkInTime' : IDL.Int,
    'manualOverride' : IDL.Bool,
    'gameDate' : IDL.Text,
    'checkOutTime' : IDL.Opt(IDL.Int),
    'overrideBy' : IDL.Opt(IDL.Text),
  });
  const CompilationStatus = IDL.Record({
    'obfuscationLayer' : IDL.Text,
    'verificationTimestamp' : IDL.Int,
    'tooltipNote' : IDL.Text,
  });
  const DirectDeposit = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isTest' : IDL.Bool,
    'userPrincipal' : IDL.Principal,
    'clearAt' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const EncryptionEvent = IDL.Record({
    'dataType' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const ExtendedStaffMember = IDL.Record({
    'id' : IDL.Text,
    'hireDate' : IDL.Int,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : IDL.Variant({
      'partTime' : IDL.Null,
      'fullTime' : IDL.Null,
      'contractor' : IDL.Null,
    }),
    'notes' : IDL.Text,
    'customRole' : IDL.Text,
    'phone' : IDL.Text,
    'employmentStatus' : IDL.Variant({
      'active' : IDL.Null,
      'inactive' : IDL.Null,
      'suspended' : IDL.Null,
    }),
  });
  const FanPoints = IDL.Record({
    'userId' : IDL.Principal,
    'totalEarned' : IDL.Float64,
    'totalRedeemed' : IDL.Float64,
    'guestContact' : IDL.Opt(IDL.Text),
    'points' : IDL.Float64,
  });
  const GDPRAuditEventType = IDL.Variant({
    'deletion_finalized' : IDL.Null,
    'deletion_requested' : IDL.Null,
    'deletion_cancelled' : IDL.Null,
    'export_requested' : IDL.Null,
  });
  const GDPRAuditEvent = IDL.Record({
    'principal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'eventType' : GDPRAuditEventType,
  });
  const GameStandAssignment = IDL.Record({
    'id' : IDL.Text,
    'gameStandId' : IDL.Text,
    'staffName' : IDL.Text,
    'staffId' : IDL.Text,
    'defaultStandId' : IDL.Text,
    'gameStandName' : IDL.Text,
    'gameDate' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const StaffMemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'removed' : IDL.Null,
  });
  const StaffMember = IDL.Record({
    'status' : StaffMemberStatus,
    'principal' : IDL.Principal,
    'joinedAt' : IDL.Int,
  });
  const DisputeStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Dispute = IDL.Record({
    'id' : IDL.Text,
    'status' : DisputeStatus,
    'submitterPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'resolution' : IDL.Opt(IDL.Text),
    'transactionTimestamp' : IDL.Int,
    'updatedAt' : IDL.Int,
    'counterpartyPrincipal' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const RecurringPayment = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'lastRunAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'totalRuns' : IDL.Nat,
    'enabled' : IDL.Bool,
    'toUser' : IDL.Principal,
    'message' : IDL.Text,
    'nextRunTime' : IDL.Int,
    'frequency' : RecurringFrequency,
    'amount' : IDL.Nat,
  });
  const RedeemedReward = IDL.Record({
    'id' : IDL.Text,
    'redeemedAt' : IDL.Int,
    'rewardTitle' : IDL.Text,
    'userId' : IDL.Principal,
    'codeOrValue' : IDL.Text,
    'rewardId' : IDL.Text,
    'contactEmail' : IDL.Opt(IDL.Text),
    'emailSent' : IDL.Bool,
  });
  const StaffInviteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const StaffInviteMethod = IDL.Variant({
    'link' : IDL.Null,
    'phone' : IDL.Null,
  });
  const StaffInvite = IDL.Record({
    'status' : StaffInviteStatus,
    'method' : StaffInviteMethod,
    'expiresAt' : IDL.Int,
    'inviteePrincipal' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'inviteCode' : IDL.Text,
    'managerPrincipal' : IDL.Principal,
  });
  const DirectDepositAccount = IDL.Record({
    'status' : IDL.Text,
    'routingNumber' : IDL.Text,
    'createdAt' : IDL.Int,
    'accountNumber' : IDL.Text,
  });
  const PartnerBrandingConfig = IDL.Record({
    'partnerName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'isActive' : IDL.Bool,
    'secondaryColor' : IDL.Text,
    'partnerLogoUrl' : IDL.Text,
  });
  const PayoutRecord = IDL.Record({
    'id' : IDL.Text,
    'distributions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'managerPrincipal' : IDL.Principal,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'declined' : IDL.Null,
  });
  const MoneyRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'toUser' : IDL.Principal,
    'message' : IDL.Text,
    'paidTipId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'fromUser' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const PointsBreakdown = IDL.Record({
    'transactionType' : IDL.Text,
    'finalPoints' : IDL.Float64,
    'amountCents' : IDL.Nat,
    'appliedRules' : IDL.Vec(
      IDL.Tuple(IDL.Text, IDL.Float64, IDL.Opt(IDL.Text))
    ),
    'basePoints' : IDL.Float64,
  });
  const SavingsDirection = IDL.Variant({
    'fromSavings' : IDL.Null,
    'toSavings' : IDL.Null,
  });
  const SavingsTransaction = IDL.Record({
    'id' : IDL.Nat,
    'direction' : SavingsDirection,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const SectionAnalytics = IDL.Record({
    'sectionName' : IDL.Text,
    'totalTips' : IDL.Nat,
    'topStaffId' : IDL.Opt(IDL.Principal),
    'totalAmount' : IDL.Nat,
    'sectionLabel' : IDL.Text,
    'staffCount' : IDL.Nat,
  });
  const SpendingLimitView = IDL.Record({
    'lastMonthReset' : IDL.Int,
    'monthlyLimit' : IDL.Opt(IDL.Nat),
    'lastWeekReset' : IDL.Int,
    'monthlySpent' : IDL.Nat,
    'lastDayReset' : IDL.Int,
    'dailyLimit' : IDL.Opt(IDL.Nat),
    'dailySpent' : IDL.Nat,
    'weeklyLimit' : IDL.Opt(IDL.Nat),
    'weeklySpent' : IDL.Nat,
  });
  const SplitPaymentStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Settled' : IDL.Null,
  });
  const SplitParticipantStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Accepted' : IDL.Null,
    'Declined' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const SplitParticipant = IDL.Record({
    'status' : SplitParticipantStatus,
    'principal' : IDL.Principal,
    'nickname' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SplitPayment = IDL.Record({
    'id' : IDL.Text,
    'status' : SplitPaymentStatus,
    'participants' : IDL.Vec(SplitParticipant),
    'initiator' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'settledAt' : IDL.Opt(IDL.Int),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TipPoolMode = IDL.Variant({ 'custom' : IDL.Null, 'equal' : IDL.Null });
  const TipPoolConfig = IDL.Record({
    'mode' : TipPoolMode,
    'enabled' : IDL.Bool,
    'customSplits' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  });
  const TipSplitRole = IDL.Record({
    'id' : IDL.Text,
    'roleName' : IDL.Text,
    'pointValue' : IDL.Float64,
    'isCustom' : IDL.Bool,
  });
  const TwoFactorSettings = IDL.Record({
    'method' : IDL.Opt(IDL.Text),
    'backupCodes' : IDL.Vec(IDL.Text),
    'enabled' : IDL.Bool,
  });
  const VaultStatus = IDL.Record({
    'unlockPending' : IDL.Bool,
    'locked' : IDL.Bool,
    'hoursRemaining' : IDL.Opt(IDL.Float64),
    'shouldShowAlert' : IDL.Bool,
  });
  const VoicePrintData = IDL.Record({
    'voicePrintHash' : IDL.Text,
    'lastVerified' : IDL.Opt(IDL.Int),
    'enrollmentDate' : IDL.Int,
  });
  const OrderItemInput = IDL.Record({
    'itemId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const SearchResult = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'isVerified' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateRewardParams = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'active' : IDL.Opt(IDL.Bool),
    'codeOrValue' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Opt(IDL.Nat),
    'pointsCost' : IDL.Opt(IDL.Nat),
    'teamId' : IDL.Opt(IDL.Text),
  });
  const PinCheckResult = IDL.Variant({
    'verified' : IDL.Null,
    'blocked' : IDL.Nat,
    'incorrect' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptStaffInvite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'acknowledgeVaultAlert' : IDL.Func([], [], []),
    'addActiveSession' : IDL.Func([ActiveSession], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text })],
        [],
      ),
    'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
    'addStatus' : IDL.Func([Status], [], []),
    'adminCloseSupportTicket' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllSupportConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SupportConversation))],
        ['query'],
      ),
    'adminGetSupportMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SupportMessage)],
        ['query'],
      ),
    'adminReplySupportMessage' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveBusinessApplication' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveTipSplitPayout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : TipSplitPayout, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignStaffSection' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : StaffSection, 'err' : IDL.Text })],
        [],
      ),
    'assignUserRole' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({
            'admin' : IDL.Null,
            'user' : IDL.Null,
            'guest' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'calculateFee' : IDL.Func(
        [
          IDL.Variant({
            'atm' : IDL.Null,
            'creditCard' : IDL.Null,
            'instantDeposit' : IDL.Null,
            'foreign' : IDL.Null,
            'businessReceive' : IDL.Null,
          }),
          IDL.Nat,
        ],
        [IDL.Nat],
        ['query'],
      ),
    'calculateTipSplit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : TipSplitPayout, 'err' : IDL.Text })],
        [],
      ),
    'cancelAccountDeletion' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelMoneyRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'cancelOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelRecurringPayment' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelSplitPayment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'cancelVaultUnlock' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'clearPartnerBranding' : IDL.Func([], [], []),
    'clearSpendingLimits' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'completeDirectDeposit' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPointsRule' : IDL.Func(
        [PointsRule],
        [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
        [],
      ),
    'createRecurringPayment' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, RecurringFrequency],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createReward' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          RewardType,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Reward, 'err' : IDL.Text })],
        [],
      ),
    'createRosterInviteLink' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createSplitPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createStand' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ConcessionStand, 'err' : IDL.Text })],
        [],
      ),
    'createStripeCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateStatus' : IDL.Func([], [], []),
    'declineStaffInvite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMenuItem' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReward' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteStand' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUserData' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteVoicePrint' : IDL.Func([], [], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'depositToSavings' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'exportUserData' : IDL.Func([], [IDL.Text], ['query']),
    'finalizeAccountDeletion' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'finalizeVaultUnlock' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'findUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'generateSmartReceipt' : IDL.Func([IDL.Nat, IDL.Nat], [SmartReceipt], []),
    'getAIQueryHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AIQuery)],
        ['query'],
      ),
    'getAccountDeletionStatus' : IDL.Func([], [DeletionStatus], ['query']),
    'getActiveOrdersForManager' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
    'getActiveSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActiveSession)],
        ['query'],
      ),
    'getAllBusinessApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessApplication))],
        ['query'],
      ),
    'getAllFraudAlerts' : IDL.Func([], [IDL.Vec(FraudAlert)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
    'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getAppLockEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getBiometricSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BiometricSettings)],
        ['query'],
      ),
    'getCallerBusinessApplicationStatus' : IDL.Func(
        [],
        [IDL.Opt(BusinessApplicationStatus)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInsForGame' : IDL.Func([IDL.Text], [IDL.Vec(StaffCheckIn)], []),
    'getCompilationStatus' : IDL.Func([], [CompilationStatus], ['query']),
    'getCurrentStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Status)],
        ['query'],
      ),
    'getDirectDepositHistory' : IDL.Func([], [IDL.Vec(DirectDeposit)], []),
    'getEncryptionLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EncryptionEvent)],
        ['query'],
      ),
    'getExtendedStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExtendedStaffMember)],
        ['query'],
      ),
    'getFanPoints' : IDL.Func([IDL.Principal], [IDL.Opt(FanPoints)], ['query']),
    'getFraudAlerts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FraudAlert)],
        ['query'],
      ),
    'getGDPRAuditLog' : IDL.Func([], [IDL.Vec(GDPRAuditEvent)], ['query']),
    'getGameStandAssignment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(GameStandAssignment)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getKYCConfigurationStatus' : IDL.Func(
        [],
        [IDL.Record({ 'provider' : IDL.Text, 'configured' : IDL.Bool })],
        ['query'],
      ),
    'getLegalAndPrivacy' : IDL.Func(
        [],
        [IDL.Record({ 'terms' : IDL.Text, 'privacy' : IDL.Text })],
        ['query'],
      ),
    'getManageMyDataAuditLog' : IDL.Func(
        [],
        [IDL.Vec(GDPRAuditEvent)],
        ['query'],
      ),
    'getManagerRoster' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getMyBusinessApplication' : IDL.Func(
        [],
        [IDL.Opt(BusinessApplication)],
        ['query'],
      ),
    'getMyDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
    'getMyFanPoints' : IDL.Func([], [IDL.Opt(FanPoints)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
    'getMyRecurringPayments' : IDL.Func(
        [],
        [IDL.Vec(RecurringPayment)],
        ['query'],
      ),
    'getMyRedeemedRewards' : IDL.Func([], [IDL.Vec(RedeemedReward)], ['query']),
    'getMyRosterInvites' : IDL.Func([], [IDL.Vec(StaffInvite)], ['query']),
    'getOrCreateDirectDepositAccount' : IDL.Func(
        [],
        [DirectDepositAccount],
        [],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(FoodOrder)], ['query']),
    'getPartnerBranding' : IDL.Func(
        [],
        [IDL.Opt(PartnerBrandingConfig)],
        ['query'],
      ),
    'getPaymentMethods' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getPendingBusinessApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessApplication))],
        ['query'],
      ),
    'getPendingDirectDeposits' : IDL.Func(
        [],
        [IDL.Vec(DirectDeposit)],
        ['query'],
      ),
    'getPendingRequestsReceived' : IDL.Func(
        [],
        [IDL.Vec(MoneyRequest)],
        ['query'],
      ),
    'getPointsBreakdown' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Text)],
        [PointsBreakdown],
        ['query'],
      ),
    'getProfessionalTips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Tip)],
        ['query'],
      ),
    'getPublicCurrentStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Status)],
        ['query'],
      ),
    'getPublicProfile' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'bio' : IDL.Text,
              'username' : IDL.Text,
              'isVerified' : IDL.Bool,
              'photo' : IDL.Opt(ExternalBlob),
              'currentStatus' : IDL.Opt(Status),
            })
          ),
        ],
        ['query'],
      ),
    'getPublicProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'bio' : IDL.Text,
              'username' : IDL.Text,
              'isVerified' : IDL.Bool,
              'photo' : IDL.Opt(ExternalBlob),
              'currentStatus' : IDL.Opt(Status),
            })
          ),
        ],
        ['query'],
      ),
    'getRequestsReceived' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
    'getRequestsSent' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
    'getReward' : IDL.Func([IDL.Text], [IDL.Opt(Reward)], ['query']),
    'getSMSConfigurationStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getSavingsBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getSavingsHistory' : IDL.Func(
        [],
        [IDL.Vec(SavingsTransaction)],
        ['query'],
      ),
    'getSectionAnalytics' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Int)],
        [IDL.Vec(SectionAnalytics)],
        ['query'],
      ),
    'getSectionAssignments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StaffSection)],
        ['query'],
      ),
    'getSecurityEvents' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SecurityEvent)],
        ['query'],
      ),
    'getSmartReceipt' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Opt(SmartReceipt)],
        ['query'],
      ),
    'getSpendingLimits' : IDL.Func([], [IDL.Opt(SpendingLimitView)], ['query']),
    'getSplitById' : IDL.Func([IDL.Text], [IDL.Opt(SplitPayment)], ['query']),
    'getSplitPayments' : IDL.Func([], [IDL.Vec(SplitPayment)], ['query']),
    'getStaffAnalytics' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Int)],
        [
          IDL.Vec(
            IDL.Record({
              'staffId' : IDL.Principal,
              'sectionName' : IDL.Opt(IDL.Text),
              'totalTips' : IDL.Nat,
              'totalAmount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getStaffSection' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StaffSection)],
        ['query'],
      ),
    'getStaffTipTotals' : IDL.Func(
        [IDL.Opt(IDL.Int)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getStatuses' : IDL.Func([IDL.Principal], [IDL.Vec(Status)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportConversation' : IDL.Func(
        [],
        [IDL.Opt(SupportConversation)],
        ['query'],
      ),
    'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
    'getTipPoolSettings' : IDL.Func([], [TipPoolConfig], ['query']),
    'getTipSplitPayouts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(TipSplitPayout)],
        [],
      ),
    'getTipSplitRoles' : IDL.Func([], [IDL.Vec(TipSplitRole)], ['query']),
    'getTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getTipsReceived' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
    'getTipsSent' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
    'getTwoFactorSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TwoFactorSettings)],
        ['query'],
      ),
    'getUnreadSupportCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVaultStatus' : IDL.Func([], [VaultStatus], ['query']),
    'getVoicePrint' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VoicePrintData)],
        ['query'],
      ),
    'hasExistingPin' : IDL.Func([], [IDL.Bool], ['query']),
    'inviteStaffByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isKYCConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'linkGuestPaymentsToUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'listExtendedStaff' : IDL.Func([], [IDL.Vec(ExtendedStaffMember)], []),
    'listMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'listPointsRules' : IDL.Func([], [IDL.Vec(PointsRule)], ['query']),
    'listRewards' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Reward)], ['query']),
    'listStands' : IDL.Func([], [IDL.Vec(ConcessionStand)], ['query']),
    'lockVault' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'logAIQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'logEncryptionEvent' : IDL.Func([EncryptionEvent], [], []),
    'logSecurityEvent' : IDL.Func([SecurityEvent], [], []),
    'logoutSession' : IDL.Func([IDL.Text], [], []),
    'manualSetHours' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
        [],
      ),
    'markSupportMessagesRead' : IDL.Func([], [], []),
    'markTutorialCompleted' : IDL.Func([], [], []),
    'openSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItemInput), IDL.Text, DeliveryMethod],
        [IDL.Variant({ 'ok' : FoodOrder, 'err' : IDL.Text })],
        [],
      ),
    'processRecurringPayments' : IDL.Func([], [], []),
    'recordCheckIn' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
        [],
      ),
    'recordCheckOut' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : StaffCheckIn, 'err' : IDL.Text })],
        [],
      ),
    'recordDisputeRequest' : IDL.Func(
        [IDL.Int, IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordExportRequest' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordGuestPayment' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          IDL.Text,
          IDL.Variant({ 'email' : IDL.Null, 'phone' : IDL.Null }),
          IDL.Opt(IDL.Text),
        ],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'guestRecordId' : IDL.Text,
              'fanPointsAwarded' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'recordPayout' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'redeemReward' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : RedeemedReward, 'err' : IDL.Text })],
        [],
      ),
    'rejectBusinessApplication' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeActiveSession' : IDL.Func([IDL.Text], [], []),
    'removeExtendedStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
    'removeStaffMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeStatus' : IDL.Func([IDL.Nat], [], []),
    'removeTipSplitRole' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeWalletAddress' : IDL.Func([], [], []),
    'reportFraudAlert' : IDL.Func([FraudAlert], [], []),
    'requestAccountDeletion' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'scheduledDeletionTime' : IDL.Int,
              'confirmationToken' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'requestMoney' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'requestVaultUnlock' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resolveDispute' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resolveFraudAlert' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'resolveUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'respondToMoneyRequest' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'respondToSplitPayment' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVoicePrint' : IDL.Func([VoicePrintData], [], []),
    'saveWalletAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendSupportMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'sendTip' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
        ],
        [],
        [],
      ),
    'sendTipWithFee' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Variant({ 'fiat' : IDL.Null, 'crypto' : IDL.Null }),
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'setAppLockEnabled' : IDL.Func([IDL.Bool], [], []),
    'setBiometricSettings' : IDL.Func([BiometricSettings], [], []),
    'setGameStandAssignment' : IDL.Func(
        [GameStandAssignment],
        [IDL.Variant({ 'ok' : GameStandAssignment, 'err' : IDL.Text })],
        [],
      ),
    'setKYCConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setKYCStatus' : IDL.Func(
        [IDL.Principal, KYCStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setPartnerBranding' : IDL.Func([PartnerBrandingConfig], [], []),
    'setPinHash' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)], [], []),
    'setSMSConfiguration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setSpendingLimits' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setTipPoolMode' : IDL.Func(
        [IDL.Bool, TipPoolMode],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setTwoFactorSettings' : IDL.Func([TwoFactorSettings], [], []),
    'setUserVerificationStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'simulateDirectDeposit' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'startWithdrawalOTPChallenge' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'expiresIn' : IDL.Nat,
              'challengeId' : IDL.Text,
              'phoneSuffix' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'submitBusinessApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitKYC' : IDL.Func([], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'togglePointsRule' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
        [],
      ),
    'toggleRecurringPayment' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePaymentMethodVerificationStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePointsRule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : PointsRule, 'err' : IDL.Text })],
        [],
      ),
    'updateReward' : IDL.Func(
        [IDL.Text, UpdateRewardParams],
        [IDL.Variant({ 'ok' : Reward, 'err' : IDL.Text })],
        [],
      ),
    'updateStand' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ConcessionStand, 'err' : IDL.Text })],
        [],
      ),
    'upsertExtendedStaff' : IDL.Func(
        [ExtendedStaffMember],
        [IDL.Variant({ 'ok' : ExtendedStaffMember, 'err' : IDL.Text })],
        [],
      ),
    'upsertTipSplitRole' : IDL.Func(
        [TipSplitRole],
        [IDL.Variant({ 'ok' : TipSplitRole, 'err' : IDL.Text })],
        [],
      ),
    'verifyPinHash' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [PinCheckResult],
        [],
      ),
    'verifyWithdrawalOTP' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'withdraw' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'withdrawFromSavings' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'withdrawWithFee' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };